- .gitignore
- README.md
- cred_helper_template.py
This makes authentication to google cloud buckets more flexible, by editing the credential helper python script and changing the username, this affects which account bazel tries to use when authenticating with the bucket
> Flexible storage account

- README.md
- cred_helper.py
This is a suggestion on how to pass the user email without relying on parsing the `.bazelrc` file with Python, but still keeping the info in the `.bazelrc` file.
> .bazelrc: do not rely on parsing username

- WORKSPACE.bazel
This PR depends on changes from https://github.com/The-OpenROAD-Project/bazel-orfs/pull/2.
Dependency on [Aspect Bazel Lib](https://github.com/aspect-build/bazel-lib) is no longer required as the implementation of `build_openroad()` macro from [bazel-orfs](https://github.com/The-OpenROAD-Project/bazel-orfs) no longer uses `run_binary()` rule from `Aspect Bazel Lib`.
CC @oharboe
> WORKSPACE: remove aspect_bazel_lib dependency

- BUILD.bazel
- entrypoint.mk
- settings.mk
Do not use `entrypoint` attribute and remove `settings.mk` which seems to be unnecessary at this point.
This change depends on https://github.com/The-OpenROAD-Project/bazel-orfs/pull/11
> Remove entrypoint

- .bazelrc
- .gitignore
This PR starts tracking `.bazelrc` file and adds `--incompatible_strict_action_env` which enables strict environment control in bazel so that env vars like PATH in the host environment are not included in the build.
> Fix env var cache invalidation

- .bazelrc
- .github/workflows/ci.yml
- .gitignore
- BUILD.bazel
- MODULE.bazel
- MODULE.bazel.lock
- WORKSPACE.bazel
- constraints-sram.sdc
- io-boomtile.tcl
- io-sram.tcl
- io-top.tcl
- io.tcl
This PR pins the version of [bazel-orfs](https://github.com/The-OpenROAD-Project/bazel-orfs) to a revision that introduces the docker flow. 
Additional changes required to enable the flow in this repository include:
* disabled bazel sandboxing feature
* Updated rules for handling SDC and IO constraints
* Changed the way `util.tcl` is sourced in SDC files and other TCL scripts
* WORKSPACE-based project configuration changed to Bzlmod
* Due to errors in CTS stage of builds, the `mock_stage` attribute was changed to `floorplan` for all build configurations
Additionally a simple CI setup was introduced to test basic build targets.
This PR depends on https://github.com/The-OpenROAD-Project/bazel-orfs/pull/16
> Introduce bazel-orfs docker flow

- out
`out` script assumed Bazel uses sandboxing. This PR corrects searched paths.
> Fix out script

- .github/scripts/build_local_target.sh
- .github/workflows/ci.yml
@oharboe
Local flow was not tested properly in megaboom. This PR adds CI tests for that and shows that the local flow indeed does not work.
In https://github.com/The-OpenROAD-Project/megaboom/actions/runs/8666007682/job/23765908357?pr=34#step:6:96 we can see that the flow fail in the same manner as it was reported.
In follow up PR (https://github.com/The-OpenROAD-Project/megaboom/pull/35) we pin `bazel-orfs` version to the one from https://github.com/The-OpenROAD-Project/bazel-orfs/pull/20 in order to fix the flow.
> CI: add local flow tests

- BUILD.bazel
Running build to test.
Without this fix, it fails with [global route congestion](https://github.com/The-OpenROAD-Project/OpenROAD/issues/4948)
> global route: reduce global route congestion with smaller meta_128x120 SRAM

- BUILD.bazel
mock SRAMs after floorplan have pathological timing
This should fix the pathological slack seen here in the clock tree. The macros is the right branch of the clock tree and the clock tree should end roughly horizontal for all elements(as little slack as possible):
> abstracts: create mock SRAMs after CTS

- out
This PR modifies behavior of `out` script, so instead of choosing the newest Bazel cache folder, its name is calculated as MD5 hash of workspace root path, as described in [Bazel docs](https://bazel.build/remote/output-directories#layout).
Moreover, `recurse` function was fixed as it's searched only one (the newest) branch, even if it was empty.
> out: Calculate cache path based on workspace path hash

- .github/workflows/ci.yml
- MODULE.bazel
- MODULE.bazel.lock
Pin [bazel-orfs](https://github.com/The-OpenROAD-Project/bazel-orfs) dependency to upstream repository. This is a follow up to https://github.com/The-OpenROAD-Project/megaboom/pull/29.
CC @oharboe
> MODULE: Use upstream bazel-orfs

- .github/workflows/ci.yml
- BUILD.bazel
…
More recent versions of ORFS have better handling of impossible timing repair after CTS and hence repair timing after CTS now fails.
The debug facilities are currently broken, so wait for those to be fixed before finding the problem with the constraint files or other settings with this test case before trying to re-enable.
> tests: create abstract for L1MetadataArray from place instead of CTS for now

- .github/scripts/build_local_target.sh
- .github/workflows/ci.yml
- MODULE.bazel
- MODULE.bazel.lock
- README.md
This PR updates bazel-orfs version to [00c6eae3cfa8bdd127928587f01e9cc38036a18a](https://github.com/The-OpenROAD-Project/bazel-orfs/tree/00c6eae3cfa8bdd127928587f01e9cc38036a18a) and adjust CI to the changes.
> Use recent bazel-orfs version

- .github/workflows/ci.yml
- MODULE.bazel
- MODULE.bazel.lock
- README.md
This PR updates version of bazel-orfs and adds testcase for `open_{stage}` targets.
> CI: Add testcase for open targets

- constraints-sram.sdc
- io-boomtile.tcl
- io-sram.tcl
- io-top.tcl
- io.tcl
@lpawelcz @eszpotanski Fewer surprises...
> orfs: fewer surprises

- .github/workflows/ci.yml
- BUILD.bazel
- MODULE.bazel
- subpackage/BUILD
- subpackage/rtl/tag_array_64x184.sv
This PR builds on top of https://github.com/The-OpenROAD-Project/bazel-orfs/pull/51 by adding a bazel `subpackage` to megaboom repository along with CI test case that verifies if `build_openroad()` macro works correctly in subpackages in external repos.
CC @oharboe @hovind
> Add subpackages

- BUILD.bazel
- MODULE.bazel
- MODULE.bazel.lock
This PR moves constraints dependencies from data to sources, so they are available during remote execution.
> Move constraints dependencies to sources

- MODULE.bazel
- README.md
This PR moves generic information to bazel-orfs and makes small cleanup.
> Move generic information to bazel-orfs

- MODULE.bazel
- MODULE.bazel.lock
- subpackage/BUILD
This PR updates bazel-orfs to current main and increase max bits for memory to avoid `Synthesized memory size exceeds maximum allowed bits 4096` [error](https://github.com/antmicro/megaboom/actions/runs/9595093561/job/26459059234#step:7:247).
> Update bazel-orfs version

- .bazelrc
- .gitignore
- README.md
- cred_helper.py
.bazelrc modifications are no longer needed
> docker vestiges: delete

- .github/scripts/build_local_target.sh
- .github/workflows/ci.yml
- MODULE.bazel
This PR updates the local flow build process and the CI workflow to improve compatibility with the latest `bazel-orfs` changes.
This PR modifies the following:
* `.github/scripts/build_local_target.sh`
* Modified flow to operate on 'in-place' stages (e.g. `do-floorplan` instead of `floorplan`)
* Modified the script to handle additional sub-stages in the synthesis (`synth`) stage, including `do-yosys-canonicalize` and `do-yosys`
* Updated logging to provide more detailed and specific output for each build and run stage
* `.github/workflows/ci.yml`
* Updated the Docker image used in the local flow to `openroad/orfs:v3.0-1114-g46acc762` to align with the one used by the project. Resolves the incompatible database schema revision error
* Removed an outdated conditional statement in the CI …
> Update CI workflow for 'Local Flow' scenario

- .github/scripts/extract_docker_revision.py
- .github/workflows/ci.yml
- MODULE.bazel
This PR introduces a script to automate the extraction of Docker image tag information within the CI workflow and integrates it into the `ci.yml` GitHub Actions workflow. The purpose of this update is to enhance the maintainability of Docker image management within the project.
This PR modifies the following:
* `.github/scripts/extract_docker_revision.py` - Added a script that parses the `MODULE.bazel.lock` file to extract the Docker image tag and SHA256 checksum
* `.github/workflows/ci.yml`
* Added a `generate-config` job to lint the `MODULE.bazel` and extract the Docker image tag using the introduced script
* Updated the `test-target-local` job to dynamically reference the Docker image and SHA256 extracted by the `generate-config` job
* `MODULE.bazel` - Removed outdated comments related …
> Automate Docker image tag extraction in CI workflow

- BUILD.bazel
floorplan.tcl takes a very long time because repair_timing is called:
https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2222/files#r1724866129
> floorplan: avoid repair_timing, which takes hours, in floorplan

- constraints-boomtile.sdc
- constraints.sdc
Reduced clock period to 1500. Will have to be revisited once we have more realistic RAMs, reduced the die area, and increased the placement density.
> reduced clock period from 6500 to 1500

- BUILD.bazel
- macros.tcl
We can easily switch back and forth between regfile macro and regfile flattened at top level, merge with master so we can inspect the artifacts.
Running times are tolerable... Largely the same.
```
Log                            Elapsed seconds Peak Memory/MB
1_1_yosys                                 7034           6011
1_1_yosys_canonicalize                      19           1421
1_1_yosys_hier_report                        0             11
No elapsed time found in logs/asap7/BoomTile/base/1_1_yosys_metrics.log
2_1_floorplan                              118           4454
2_2_floorplan_io                            14           2798
No elapsed time found in logs/asap7/BoomTile/base/2_3_floorplan_tdms.log
2_4_floorplan_macro                         16           2757
No elapsed time found …
```
> Floorplan regfile flip flops

- BUILD.bazel
- MODULE.bazel
- MODULE.bazel.lock
- report-sram.tcl
- sram.py
@jeffng-or To generate a report with information about all the SRAMs, run:
```
$ bazel run sram_report
[deleted]
INFO: Running command line: bazel-bin/sram_report ./ebtb_128x40.yaml ./array_256x128.yaml ./dataArrayB_256x64.yaml ./tag_array_64x184.yaml ./tag_array_64x168.yaml ./table_256x48.yaml ./table_128x52.yaml ./table_128x44.yaml ./btb_128x56.yaml ./meta_128x120.yaml ./lb_32x128.yaml ./sdq_17x64.yaml ./data_2048x8.yaml ./mem_256x4.yaml ./meta_40x240.yaml
```
Outputs:
| Name              |   width |   height | in2out   |   in2reg |   reg2out |   reg2reg |
|:------------------|--------:|---------:|:---------|---------:|----------:|----------:|
| ebtb_128x40       |   40.04 |    30.53 | N/A      |   354.98 |    332.81 |    563.21 |
| array_256x128     |   87.58 |    42.22 | N/A      | …
> Sram tweaks

- README.md
- cred_helper.py
```
$ ./cred_helper.py
Running: gcloud auth print-access-token oyvind@openroad.tools {
"kind": "storage#testIamPermissionsResponse",
"permissions": [
"storage.buckets.get",
"storage.objects.create"
]
}
```
> cred_helper: add test mode, run without arguments

- MODULE.bazel
@jeffng-or I'm confused... Trying a bump to see if the problem is fixed.
```
bazel run BoomTile_cts `pwd`/tmp
tmp/make gui_cts
```
Fails on main:
```
external/bazel-orfs~~orfs_repositories~docker_orfs/OpenROAD-flow-scripts/flow/Makefile:177: platforms/asap7/config.mk: No such file or directory
make: *** No rule to make target 'platforms/asap7/config.mk'.  Stop.
```
Also:
```
$ bazel run BoomTile_cts `pwd`/tmp  gui_cts
[deleted]
bazel-bin/results/asap7/BoomTile/base/4_cts.odb
bazel-bin/results/asap7/BoomTile/base/4_cts.sdc
INFO: Elapsed time: 0.107s, Critical Path: 0.04s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/BoomTile_cts.sh /home/oyvind/megaboom/tmp gui_cts …
```
> bazel-orfs: bump

- constraints-boomtile.sdc
- constraints.sdc
Sped up clock to 833 MHz.
Design metrics:
Design area: 787840 (prev: 784518)
Utilization: 35%: no change
tns: -128,422,560.00 (prev: -421,436,256.00)
wns: -1966.33 (prev: -5636.75) WNS is in reg2reg path
clock_skew: 122 (prev: 319)
CTS latency: 940 (prev: 1924)
clock tree still has one segment that's unbalanced, so no change but will investigate more:
Artifacts exist for this run, so CI should go quickly and anyone can pull down the artifacts. Artifact pulldown verified through clean workspace.
> changed clock period to 1200 / 833 MHz

- BUILD.bazel
- plot-3d-slack.py
- slack-positions.tcl
Run `bazel run show_slack`, and you get an interactive 3d graph of the slack as a function of position for the 1000 WNS paths.
@precisionmoon @maliberty @jeffng-or What I really wanted was CTS skew as a function of x/y position plotted in 3d.
This is based on some old ideas in this [discussion](https://github.com/The-OpenROAD-Project/OpenROAD/discussions/3788)
> slack: add 'bazel run show_slack' that show slack in 3d

- etc/BuildMegaboom.sh
short and sweet, reads easier.
> build: less verbose build script, use bash error handling

- BUILD.bazel
Stage: cts
| Variant                   | base        | 1            | 3            |
|---------------------------|-------------|--------------|--------------|
| crpr                      | 1.52        | 1.52         | 2.13         |
| skew                      | 113.21      | 113.21       | 139.94       |
| slack                     | -1553.49646 | -1553.906128 | -1565.608154 |
| tns                       | -80420496.0 | -80496816.0  | -78941104.0  |
| GPL_ROUTABILITY_DRIVEN    |             |              |              |
| GPL_TIMING_DRIVEN         |             |              | 1            |
| SETUP_SLACK_MARGIN        |             |              | -1000        |
| SKIP_CTS_REPAIR_TIMING    |             | 0            | 0            |
| SKIP_INCREMENTAL_REPAIR   |             | …
> sweep: sweep some optimizations

- BUILD.bazel
- report-wns.tcl
Waiting for variant 2, here is the table so far:
Stage: cts
| Variant                   | base         | 1            | 3            |
|---------------------------|--------------|--------------|--------------|
| crpr                      | 11.47        | 11.47        | 21.8         |
| skew                      | 362.76       | 362.76       | 351.29       |
| slack                     | -4490.124023 | -4380.438965 | -4755.364746 |
| tns                       | -381370656.0 | -374684800.0 | -376241280.0 |
| GPL_ROUTABILITY_DRIVEN    |              |              |              |
| GPL_TIMING_DRIVEN         |              |              | 1            |
| SETUP_SLACK_MARGIN        |              |              | -1000        |
| SKIP_CTS_REPAIR_TIMING    |              | 0            | 0 …
> report: use open.tcl which reads in timing properly

- BUILD.bazel
avoids wasting build resources and gets us an .odb and .rpt file to examine.
@maliberty @jeffng-or FYI
> global route: do a few iterations since grt is futile for now

- wns_report.py
Stage: cts
| Variant                   | base                          | 1            | 2                                 |
|---------------------------|-------------------------------|--------------|-----------------------------------|
| crpr                      | 15.04                         | 15.02        | 15.49                             |
| skew                      | 452.64                        | 583.52       | 575.04                            |
| slack                     | -4618.476074                  | -5494.812988 | -3262.439697                      |
| tns                       | -384685088.0                  | -451544224.0 | -97992368.0                       |
| MACRO_PLACEMENT_TCL       |                               |              | $(location write_macro_placement) …
> wns_report: include dissolved macros line

- BUILD.bazel
@maliberty @jeffng-or Trying flattend synthesis with automatic macro placement because flattening synthesis reduces number of instances with 50%.
Best WNS is variant 6:
clock tree, skew is worst case on the order of 500ps overall, but the skew is 73 for the worst path, so an improved CTS won't move the needle on WNS.
Worst WNS routing has ca. 50% logic delay, logic depth 61, the rest is routing. 61 levels of logic. The documentation of BOOM clearly states that [the floating point unit must be register retimed](https://docs.boom-core.org/en/latest/sections/physical-realization.html)
RUDY routing congestion; seems like it should be possible to make it pass grt.
```
>>> report_checks -path_group reg2reg -fields {fanout slew}
Startpoint: dcache.s1_valid_REG_1$_SDFF_PP0_
(rising edge-triggered …
```
> Macro placement flattened synthesis

- BUILD.bazel
The description of the variant says last gasp enabled, but it was actually disabled
> variants: fix variant, last gasp enabled

- MODULE.bazel
- MODULE.bazel.lock
@maliberty @jeffng-or FYI
Running times are very well contained even when all repair is enabled, but WNS is 10% worse than it used to be, -3300 vs -2700.
Stage: cts
| Variant                        | base                                                                | 1                                                            | 2                                                                                     |
|--------------------------------|---------------------------------------------------------------------|--------------------------------------------------------------|---------------------------------------------------------------------------------------|
| Description                    | Base settings, provides macro placement from hierarchical synthesis | Flattend, timing …
> orfs: bump

- BUILD.bazel
- Introduce OTHER_VARIANTS, variants that are not part
of the sweep, but used for other testing purposes or
from SWEEP variants.
- BoomTile has pathological resource usage when not flattened
regardless of MAX_UNGROUP_SIZE(we have done a sweep to drive
a wooden stake through the heart of the idea that some magic
value of MAX_UNGROUP_SIZE will 'fix' hiearchical synthesis for
megaboom), so non-flattened synthesis is not interesting
to examine in megaboom. Upcoming work in OpenROAD will probably
restore the usefulness of studying hierarchical synthesis
results in OpenROAD since eliminating unused logic after
hierarchical synthesis is known (from naja) to reduce
instances in megaboom by 50%.
> sweep: cleanup

- BUILD.bazel
- etc/BuildMegaboom.sh
@jeffng-or FYI, add a sweep_parallel filegroup to build stuff in parallel and then afterwards build grt in serial
> ci: support building grt in sweeps

- BUILD.bazel
- MODULE.bazel
- constraints-boomtile.sdc
- pdn.tcl
Branch predictor macros visible:
WNS from gui_floorplan:
Stage: cts
| Variant                        | base                              | 1                                         |
|--------------------------------|-----------------------------------|-------------------------------------------|
| Description                    | Flattend, timing driven placement | Hierarchical, branch predictors as macros |
| Buffer                         | 118586                            | 246303                                    |
| Clock buffer                   | 12894                             | 20569                                     |
| Clock inverter                 | 3737                              | 5945                                      |
| Inverter                       | 70385 …
> megaboom: branch predictors as macros

- BUILD.bazel
place density 0.69 is the end of the line, 0.73 didn't make it past placement.
Looks like the diea area could come down a bit more.
Stage: cts
| Variant                        | base                              | 1                                 | 2                                 | 3                                 |
|--------------------------------|-----------------------------------|-----------------------------------|-----------------------------------|-----------------------------------|
| Description                    | Flattend, timing driven placement | Placement density sweep           | Placement density sweep           | Placement density sweep           |
| Buffer                         | 118587                            | 118587                            | 118587 …
> floorplan: 1250x1250

- MODULE.bazel
- MODULE.bazel.lock
@maliberty @jeffng-or FYI, there is a script in bazel-orfs `bump.sh` that updates MODULE.bazel in projects that use bazel-orfs with the latest ORFS + bazel-orfs.
1. run `bazel run @bazel-orfs//:bump`, this updates MODULE.bazel. bazel mod tidy does the more verbose MODULE.bazel.lock update.
2. create a PR such as this one
> bump: orfs and bazel-orfs
