The-OpenROAD-Project/megaboom

bazel.mk, openroad.bzl
disappointingly, bazel rebuilds synth, even if the hash of the clock period did not change
=> sdc: clock period is now a separate dependency

BUILD.bazel, bazel.mk, constraints-digitaltop.sdc, openroad.bzl
Not knowing anything about these clocks, assume they are the same as the existing clock, for now.
=> DigitalTop: add two more clocks

README.md, cred_helper.py
@maliberty @tspyrou Unfortunately, the new nicer approach doesn't work. I don't know that it can be made to work either..
@vvbandeira Do you want to have another go at it?
=> Credential helper revert

.github/workflows/ci.yml, BUILD.bazel
This PR adds job with linting Basel-specific code and removes unused variables.
=> Add job with linter

BUILD.bazel
@lpawelcz FYI. Requires https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1912
=> cts: skip timing repair, hopeless for now

.github/workflows/ci.yml
Change the design to build from `BoomTile` to `lb_32x128`
=> CI: Don't build BoomTile

README.md
@oharboe
This PR depends on https://github.com/The-OpenROAD-Project/bazel-orfs/pull/27. Some of the instructions added here refer to GUI targets that are yet to be introduced to bazel-orfs. After merging https://github.com/The-OpenROAD-Project/bazel-orfs/pull/27 we should pin new `bazel-orfs` version in [MODULE.bazel](https://github.com/The-OpenROAD-Project/megaboom/blob/main/MODULE.bazel#L11) and then merge this PR.
We also decided to remove `Creating an issue report` paragraph because we feel that it belongs to `bazel-orfs` documentation and will be added there alongside the support for `make issue` targets.
Perhaps most of the `Tutorial` chapter should eventually end up in `bazel-orfs`.
Please let us know what do you think.
=> README: Update the usage instructions

BUILD.bazel
=> synthesis: fix SRAM errors

MODULE.bazel
=> build: remove sharp corner from comment on how to test locally

.github/workflows/ci.yml
This PR shorten the CI and job names
=> CI: Make job names shorter

BUILD.bazel
@lpawelcz @maliberty FYI
Needs https://github.com/The-OpenROAD-Project/bazel-orfs/pull/37
=> Dry boomtile

BUILD.bazel, MODULE.bazel, mock/data_2048x8.sv, mock/tag_array_64x184.sv
=> Mock faster tests

BUILD.bazel
=> megaboom: disable timing driven placement for faster global place

MODULE.bazel, MODULE.bazel.lock
Procedure:
1. updated ORFS in MODULE.bazel
2. ran: `bazel mod tidy`
3. commit MODULE.bazel*
=> ORFS: latest

MODULE.bazel
@hovind How do I test with a locally built docker image?
=> Docker locally built

.github/scripts/build_local_target.sh
This PR adds support for pre-synthesis canonicalize stage to scripts testing dependency targets in CI
=> Support orfs_canonicalize in scripts testing dependency targets

.github/scripts/build_local_target.sh, MODULE.bazel, MODULE.bazel.lock
=> bazel-orfs: latest

MODULE.bazel, MODULE.bazel.lock
@jeffng-or FYI, building artifacts...
=> ORFS: v3.0-1206-gc6ea30d2

MODULE.bazel, MODULE.bazel.lock
@jeffng-or Building arfitacts before merging. Don't know why, but synthesis had to be redone.
=> bazel-orfs: upgrade

BUILD.bazel
=> floorplan: set PDN_TCL for top level

BUILD.bazel
=> cts: skip repair, takes too long for now

BUILD.bazel
=> grt: save time by skipping repair

.github/scripts/build_local_target.sh, MODULE.bazel, MODULE.bazel.lock
=> bazel-orfs: bump

BUILD.bazel, MODULE.bazel
=> BoomTile: automatically assign variables to stages

BUILD.bazel
grt passes without routing congestion failures
=> Updated placement density to 0.2

BUILD.bazel, MODULE.bazel, MODULE.bazel.lock, macros.tcl
Macro placement and floorplan surgery...
There's no obvious way to do an master/PR comparision or what to compare... This is not 
*obviously* different, but it does answer the question as to what would happen if we flattened the design with the current macro placement.
=> BoomTile: hierarchical synthesis is only neede to record macro placement

BUILD.bazel, MODULE.bazel, MODULE.bazel.lock
=> BoomTile: skip tap & fill cells

BUILD.bazel, jenkins/genReport.py
previous Jenkins run didn't report a failure when it should. Updating genReport.py exit code to return non-zero when there are errors in the log.
=> testing genReport & Jenkins reporting failure

constraints.sdc
PR to update SRAM SDC file to define both clocks
=> updated SDCs to define both read and write clocks

docker/Dockerfile.dev
sending up just the addition of the time cmd to a PR
=> added missing time cmd to dockerfile

MODULE.bazel, MODULE.bazel.lock
=> bump bazel-orfs to f665761

MODULE.bazel.lock, etc/BuildMegaboom.sh, jenkins/public_build.Jenkinsfile
Moved command to build BoomTile from jenkins-ci to megaboom repo
Added testing of cred_helper.py before BoomTile build
=> Added megaboom build script for CI

BUILD.bazel, report-kpi.tcl
KPI - Key Performance Indicator
@jeffng-or Please amend to generate an "official" yaml KPI report with the [metrics](https://github.com/The-OpenROAD-Project/megaboom/pull/156) that are important.
```
bazel build kpi
```
=> report: skeleton KPI report

BUILD.bazel, docker/Dockerfile.dev, etc/BuildMegaboom.sh, report-wns.tcl, wns_report.py
Stage: cts
| Variant                   | base         |               1 |               2 |               3 |               4 |
|---------------------------|--------------|-----------------|-----------------|-----------------|-----------------|
| crpr                      | 2.13         |     2.1         |     1.94        |     1.37        |     1.37        |
| skew                      | 122.0        |   153.47        |   121.37        |   135.87        |   147.38        |
| slack                     | -1966.328857 | -1766.3         | -1752.46        | -1838.15        | -2002.13        |
| tns                       | -128422560.0 |    -1.14426e+08 |    -1.04185e+08 |    -1.23248e+08 |    -1.10018e+08 |
| PLACE_DENSITY             |              |     0.25        |     0.21        | …
=> Sweep first cut

BUILD.bazel, MODULE.bazel, MODULE.bazel.lock
@jeffng-or @maliberty Repair timing added.
Built an ORFS image locally and published it as a stopgap while we're waiting for all the pending changes to land in ORFS official docker image.
=> Orfs repair timing

BUILD.bazel, MODULE.bazel.lock, plot-retiming.py
The idea is to plot retiming progress against iterations:
```
bazel build plot_repair
```
=> Plot retiming

BUILD.bazel, MODULE.bazel, MODULE.bazel.lock
Stage: cts
| Variant                   | base         | 1            | 2                                 |
|---------------------------|--------------|--------------|-----------------------------------|
| crpr                      | 15.04        | 15.02        | 15.49                             |
| skew                      | 452.64       | 583.52       | 575.04                            |
| slack                     | -4618.476074 | -5494.812988 | -3262.439697                      |
| tns                       | -384685088.0 | -451544224.0 | -97992368.0                       |
| MACRO_PLACEMENT_TCL       |              |              | $(location write_macro_placement) |
| PLACE_DENSITY             |              |              |                                   |
| REMOVE_ABC_BUFFERS …
=> Sram aspect ratio nearer 1

BUILD.bazel
stop dissolving register files
=> variants: improve readability with less iffy code

BUILD.bazel
Stage: cts
| Variant                        | base         | 2                                         | 3                                                 |
|--------------------------------|--------------|-------------------------------------------|---------------------------------------------------|
| Description                    |              | Same as base, but with flattend synthesis | Same as base, only with CTS timing repair enabled |
| Buffer                         | 264492       | 119157                                    | 264492                                            |
| Clock buffer                   | 23052        | 12067                                     | 23052                                             |
| Clock inverter                 | 6997         | 3634 …
=> Cts differ only

BUILD.bazel
hopefully this will fix the global placement issues for now
@gudeh FYI, shot in the dark...
=> floorplan: bump size to 1300x1300

MODULE.bazel, MODULE.bazel.lock
@jeffng-or Should be safe, but stand back, it has been a while...
=> orfs: bump

.bazelrc, .gitignore
=> user.bazelrc: consistency with OpenROAD/bazel standard

BUILD.bazel, MODULE.bazel, MODULE.bazel.lock
=> BoomTile: retime
